### Site metadata

title: Lydia van Fondern
description: A gallery of images by Lydia van Fondern

url: "https://artists-portfolio.netlify.app"
baseurl: ""

github_username: "lydiavanfondern"
repository: "lydiavanfondern/lydiavanfondern.github.io"

google_analytics_key: ""

# For SEO tag.
logo: /siteicon.png
author:
  name: Lydia van Fondern
  twitter:
social:
  name: Lydia van Fondern gallery
  links:
    - https://github.com/lydiavanfondern/lydiavanfondern.github.io

### Build settings

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      text_width: true
  - scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - LICENCE-source
  - Makefile
  - netlify.toml
